name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies if requirements.txt exists
        run: |
          if [ -f requirements.txt ]; then
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          else
            echo "No requirements.txt found, skipping dependency installation."
          fi   

      

      - name: Run Python script
        run: python your_test.py

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v4.0.0
        with:
          projectKey: Samron10_ProjectNTT
          organization: samron10
          token: ${{ secrets.SONAR_TOKEN }}

